version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on: 
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cookbook_admin
      - POSTGRES_PASSWORD=tsting_djngo123
      - POSTGRES_DB=cookbook

volumes:
  postgres_data:



#   postgres:
#     image: postgres
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_USER=cookbook_admin
#       - POSTGRES_PASSWORD=tsting_djngo123
#       - POSTGRES_DB=cookbook
#     ports:
#       - 5432:5432
#     healthcheck:
#       test: ["CMD", "pg_isready"]
#       timeout: 5s
#       retries: 3
#     env_file:
#       - ./.env.dev
  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
     # - postgres
      # - migration
    # environment:
    #   - POSTGRES_HOST=postgres
    #   - POSTGRES_USER=cookbook_admin
    #   - POSTGRES_PASSWORD=tsting_djngo123
    #   - POSTGRES_DB=cookbook
    # environment:
    #   port: '8000'
    # env_file:
    #   - ./.env.dev
#   # migration:
#   #   build: .
#   #   command: python manage.py migrate --noinput
#   #   volumes:
#   #     - ./pgdata:/var/lib/postgresql/data/pgdata
#   #   environment:
#   #     - POSTGRES_HOST=postgres
#   #     - POSTGRES_DB=cookbook
#   #     - POSTGRES_USER=cookbook_admin
#   #     - POSTGRES_PASSWORD=tsting_djngo123
#   #   env_file:
#   #       - ./.env.dev
#   #   depends_on: 
#   #     - postgres
# volumes:
#   postgres_data: